### ISSUE TITLE
[EPIC Django Tests] Summary of tests for Django

### ISSUE THREAD

**Issue by luabida** [Mosqlimate-project/Data-platform#27]
## main:
- [ ] **Views**
  - [ ] home()
  - [ ] about()
  - [ ] docs()
  - [ ] error_404()
- [ ] **Schema**
  - [ ] SuccessSchema
  - [ ] ForbiddenSchema
  - [ ] NotFoundSchema
- [ ] **API**
  - [ ] on_invalid_token()

## users:
 - [ ] **Models**
    - [ ] CustomUser
      - [ ] save()
      - [ ] get_fullname()
    - [ ] CustomUserManager
      - [ ] create_user()
      - [ ] create_superuser()  
    - [ ] create_author() # signal
- [ ] **Views**
  - [ ] profile()
  - [ ] redirect_to_user_profile()
  - [ ] logout_github()
- [ ] **Schema**
  - [ ] UserSchema
  - [ ] UserInPost
- [ ] **API**
  - [ ] update_user()
- [ ] **Auth**
  - [ ] UidKeyAuth
    - [ ] authenticate()
    - [ ] validate_uid_key() 
    
## registry:
 - [ ] **Models**
    - [ ] Author
    - [ ] Model
    - [ ] Prediction
- [ ] **Views**
  - [ ] profile()
  - [ ] redirect_to_user_profile()
  - [ ] logout_github()
- [ ] **Schema**
  - [ ] UserSchema
  - [ ] UserInPost
- [ ] **API**
  - [ ] AuthorIn
  - [ ] AuthorInPost
  - [ ] list_authors()
  - [ ] get_author()
  - [ ] create_author()
  - [ ] update_author()
  - [ ] delete_author()
  - [ ] ModelIn
  - [ ] ModelInUpdate
  - [ ] list_models()
  - [ ] get_model()
  - [ ] create_model()
  - [ ] delete_model()
  - [ ] PredictionIn
  - [ ] list_predictions()
  - [ ] get_prediction()
  - [ ] create_prediction()
  - [ ] update_prediction()
  - [ ] delete_prediction()
- [ ] **Utils**
  - [ ] calling_via_swagger()

## datastore:
  - TBD
