### ISSUE TITLE
[EPIC Django Docs] Summary of Documentation

### ISSUE THREAD

**Issue by luabida** [Mosqlimate-project/Data-platform#31]
- [ ] **Choose Documentation template/engine** (question)

---

- [ ] API calls
  - [ ] Authenticate with `X-UID-Key`
  - [ ] Calls using `curl` (shell)
  - [ ] Calls using `python` (requests)
  - [ ] Calls using `R` (?)

---

- [ ] `registry` Models
  - [ ] Explain `Models` fields
  - [ ] Explain `Predictions` fields

---

- [ ] `datastore` Models
   - TBD

**Comment by fccoelho** [comment]
We normally use  (I am more familiar with) sphinx, but I guess we can try Mkdocs for a change. It apparently works with readthedocs.org, so it may be a good option.
